// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise";
import type {
  HealthCheckResponse,
  UploadTranscribeAudioData,
  UploadTranscribeAudioResponse,
} from "./types.gen";
import { OpenAPI } from "./core/OpenAPI";
import { request as __request } from "./core/request";

/**
 * Check
 * Secured health check endpoint.
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const healthCheck = (): CancelablePromise<HealthCheckResponse> => {
  return __request(OpenAPI, {
    method: "GET",
    url: "/v1/health",
    errors: {
      404: "Not found",
    },
  });
};

/**
 * Transcribe Audio
 * Endpoint to upload and process audio files with OpenAI Whisper.
 * @param data The data for the request.
 * @param data.formData
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const uploadTranscribeAudio = (
  data: UploadTranscribeAudioData,
): CancelablePromise<UploadTranscribeAudioResponse> => {
  return __request(OpenAPI, {
    method: "POST",
    url: "/v1/upload",
    formData: data.formData,
    mediaType: "multipart/form-data",
    errors: {
      404: "Not found",
      422: "Validation Error",
    },
  });
};
